### ISSUE TITLE
Works in Zabbix 2.4.8

### ISSUE THREAD

**Issue by clarkritchie** [greatcare/pm2-zabbix#10]
Fantastic daemon!  :clap:  I got it working with our web front ends running Ubuntu 16.04 using a Zabbix 2.4.8 server.  Happy to post more details, if needed.

**Comment by rkaw92** [comment]
Great news. Sure, if you have any feedback or information on the steps it takes, go ahead. It could be useful to include this procedure, along with any gotchas, on the wiki or even in an additional readme-type file.

**Comment by clarkritchie** [comment]
Install on Ubuntu 16.04:

```
sudo apt-get install zabbix-sender
sudo npm install -g pm2-zabbix
# test: pm2-zabbix --discover
# run interactively:  pm2-zabbix --monitor
```

This installed as `/usr/bin/pm2-zabbix` -- not `/usr/local/bin/pm2-zabbix` as in the examples.  Also, the user is ubuntu -- not debian.  So configure for systemd:

```
# swap debian for ubuntu and remove local from path
wget -qO - https://raw.githubusercontent.com/greatcare/pm2-zabbix/master/install/init/systemd/pm2-zabbix.service | sed 's/\/local//' | sed 's/debian/ubuntu/' | sudo tee /etc/systemd/system/pm2-zabbix.service
```

Edit `sudoers` as per #1, adding:
```
zabbix  ALL=(ALL:ALL) NOPASSWD: /usr/bin/pm2-zabbix
```

```
sudo systemctl enable pm2-zabbix
sudo systemctl start pm2-zabbix
# stop:  sudo systemctl stop pm2-zabbix
# restart:  sudo systemctl restart pm2-zabbix
```

Add the `UserParameter` to Zabbix agent and restart:
```
wget -qO - https://raw.githubusercontent.com/greatcare/pm2-zabbix/master/install/zabbix-agent/pm2-zabbix.conf | sed s/debian/ubuntu/ | sudo tee /etc/zabbix/zabbix_agentd.d/pm2-zabbix.conf

sudo systemctl restart zabbix-agent
```

Here is my template [Template App PM2](https://gist.github.com/clarkritchie/bfdf9960cfe46c821b06f76e388c7894) as exported from Zabbix 2.4.8.  It's still work in progress -- but the Item prototypes work, I'm still tweaking/testing the Trigger prototypes.

Thanks again!

**Comment by rkaw92** [comment]
I've posted the steps to here (and bootstrapped the wiki along the way):
https://github.com/greatcare/pm2-zabbix/wiki/Install-on-Ubuntu-16.04

Thanks for the contribution - really appreciated. Not closing the issue at the moment in case you have more insight as to the triggers.

**Comment by clarkritchie** [comment]
I'll post an update in a bit when I have them dialed in.

**Comment by rkaw92** [comment]
I don't suppose the wiki is getting an improvement w.r.t. installing on Ubuntu 16.04 any time soon. Closing.
