### ISSUE TITLE
sysvinit script needs --monitor

### ISSUE THREAD

**Issue by clarkritchie** [greatcare/pm2-zabbix#11]
I think this needs `--monitor` -- yes?   https://github.com/greatcare/pm2-zabbix/blob/master/install/init/sysv/pm2-zabbix#L47

**Comment by rkaw92** [comment]
Yes. Sorry about this oversight. Fixing it soon for 0.2.1. This has actually been noticed in #8 .

**Comment by rkaw92** [comment]
Okay, v0.2.1 is up.
