### ISSUE TITLE
Graph-Discrepency-LatestData vs Graph prototype

### ISSUE THREAD

**Issue by ang3lwitch** [greatcare/pm2-zabbix#30]
So, I have used pm2-zabbix for about 1 year, works great. Thanks for that.

It came to my attention from a developer in that the following visuals are troublesome.

If, for instance a particular application, "pm2-api_app" climbs in memory usage
pm2-zabbix does do its job, sends an alert and from "Monitoring->Latest-Data->Host-Pm2-app
it shows proper spikes/triggers in graph.

If I were to select same host and go right to graphs, bypassing "Latest Data"
The graph is not to the same scale and does not show the correct memory usage, meaning much lower
than that of "Latest Data"

I understand that graph prototype may not have the trigger lines in it, that is fine.
I just would like to know why the discrepancy happens from the graph prototype vs latest data graph
for the same application's memory check.

Thanks

**Comment by dcdamien** [comment]
Hi @ang3lwitch, thank you for reporting this issue.
Unfortunately I'm not able to reproduce problem you've described.

This is how it looks on our instance on example item, I don't see any difference:

#### graphs:

![image](https://user-images.githubusercontent.com/7643344/51052780-0905b900-15d8-11e9-8967-617e9314a9fa.png)

#### latest data:

![image](https://user-images.githubusercontent.com/7643344/51052791-0d31d680-15d8-11e9-8293-0be53393958d.png)
