### ISSUE TITLE
zabbix-server no data

### ISSUE THREAD

**Issue by kaishidongle90** [greatcare/pm2-zabbix#6]
hello, thanks for your document, I did with your document , but now the zabbix-server has no date , I cannot find where I'am wrong , every step is the same you said  ,  and. my zabbix-servser is 3.2 can I use your template and could you tell me how can I test  form zabbix-client to zabbix-server thanks

**Comment by kaishidongle90** [comment]
I just find the website https://github.com/greatcare/pm2-zabbix/issues/2    I have the same error with him  I have already fixed, thanks again

**Comment by rkaw92** [comment]
Is your problem fixed entirely, then? Can we close this?

**Comment by kaishidongle90** [comment]
yes It's done thanks
