### ISSUE TITLE
Not sending CPU/Memory stats; release new version?

### ISSUE THREAD

**Issue by c0bra** [greatcare/pm2-zabbix#9]
None of the process resource usage info seems to be coming up to Zabbix.

There's a commit from Jan 26th that updates to the "new" PM2 api,  but it hasn't been released as the latest version (0.1.2) is from last April (2016). 

@rkaw92 could you cut a new release, please?

**Comment by c0bra** [comment]
Alright, not 100% sure if that was the issue but I manually installed the tarball for commit 181959e and it's working.

**Comment by rkaw92** [comment]
Hi, I've just published 0.2.0 with the updated pm2 integration code. Let me know should you encounter any further trouble. If you are confident that the matter is settled, feel free to close this issue.

**Comment by penguin02007** [comment]
I am using 0.2.1 and seeing the same issue, thoughts?

`/home/foo └─┬ pm2-zabbix@0.2.1  ├── minimist@1.2.0  ├── pidusage@1.1.5`


```
$ sudo PM2_HOME=/etc/data/hypernova/pm2 pm2-zabbix --discover
{
        "data": [
                {
                        "{#PROCESS_ID}": "hypernova_service-0",
                        "{#PROCESS_NAME}": "hypernova_service"
                },
                {
                        "{#PROCESS_ID}": "hypernova_service-1",
                        "{#PROCESS_NAME}": "hypernova_service"
                },
                {
                        "{#PROCESS_ID}": "hypernova_service-2",
                        "{#PROCESS_NAME}": "hypernova_service"
                }
        ]
```

**Comment by rkaw92** [comment]
@penguin02007 Hi. The discovery result looks OK relative to the pm2 status. Is pm2-zabbix not sending anything? Is it failing with an error? Have you checked the [Troubleshooting](https://github.com/greatcare/pm2-zabbix/blob/master/Troubleshooting.md) guide? If yes, please open a new issue and describe the exact symptoms you are seeing vs. the expected behavior.

**Comment by penguin02007** [comment]
I didn't go that far to start sending data to zabbix as there are metrics missing. I will open a new issue for this. Thanks!
